{{ range $key, $val := .Values.components }}
{{- if eq $val.state "enabled" -}}
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: {{ printf "nscfg-%s%s" $key $.Values.naming.namespaceSuffix | replace "_" "-" }}
spec:
  force: false
  interval: 1m0s
  path: ./
  prune: true
  retryInterval: 1m0s
  serviceAccountName: flux-applier
  sourceRef:
    kind: GitRepository
    name: {{ printf "lscsde-namespace%s" $.Values.naming.namespaceSuffix }}
    namespace: {{ $.Release.Namespace }}
  timeout: 1m0s
  wait: false
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: {{ printf "nscfg-%s%s" $key $.Values.naming.namespaceSuffix | replace "_" "-" }}
---
{{- end -}}
{{ end }}